export const EVENT_STATUS = {
  DRAFT: 'DRAFT',
  LIVE: 'LIVE',
  PAUSED: 'PAUSED',
  COMPLETED: 'COMPLETED'
};

export const HEALTH_STATUS = {
  ON_SCHEDULE: 'ON_SCHEDULE',
  RUNNING_LATE: 'RUNNING_LATE',
  DISRUPTED: 'DISRUPTED'
};

export const SESSION_STATUS = {
  UPCOMING: 'UPCOMING',
  LIVE: 'LIVE',
  COMPLETED: 'COMPLETED',
  SKIPPED: 'SKIPPED',
  DELAYED: 'DELAYED',
  CANCELLED: 'CANCELLED'
};

export const ANNOUNCEMENT_TYPE = {
  DELAY: 'DELAY',
  EMERGENCY: 'EMERGENCY',
  STAGE_DIRECTION: 'STAGE_DIRECTION',
  GENERAL: 'GENERAL'
};

export const URGENCY_LEVEL = {
  LOW: 'LOW',
  MEDIUM: 'MEDIUM',
  HIGH: 'HIGH',
  CRITICAL: 'CRITICAL'
};

export const QUESTION_STATUS = {
  PENDING: 'PENDING',
  APPROVED: 'APPROVED',
  REJECTED: 'REJECTED',
  ANSWERED: 'ANSWERED'
};
