export const MOCK_USER_ORGANIZER = {
  id: 'usr_org_101',
  name: 'Elena Rostova',
  email: 'elena@stagepilot.io',
  role: 'organizer',
  avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  eventAccess: ['evt_001', 'evt_002'],
};

export const MOCK_USER_ANCHOR = {
  id: 'usr_anc_202',
  name: 'Marcus Vance',
  email: 'marcus@stagepilot.io',
  role: 'anchor',
  avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80',
  assignedStage: 'Main Stage',
};

export const MOCK_TRACKS = [
  {
    id: 'track_a',
    code: 'TRACK_A',
    name: 'TRACK A — MAIN STAGE',
    shortName: 'Track A',
    venue: 'Main Auditorium Stage A',
    delayMinutes: 10,
    status: 'RUNNING_LATE',
    color: 'cyan',
    activeAgendaId: 'agenda_02',
  },
  {
    id: 'track_b',
    code: 'TRACK_B',
    name: 'TRACK B — WORKSHOP HALL',
    shortName: 'Track B',
    venue: 'Workshop Hall B',
    delayMinutes: 0,
    status: 'ON_SCHEDULE',
    color: 'emerald',
    activeAgendaId: 'agenda_b2',
  },
  {
    id: 'track_c',
    code: 'TRACK_C',
    name: 'TRACK C — NETWORKING LOUNGE',
    shortName: 'Track C',
    venue: 'Foyer Stage C',
    delayMinutes: 5,
    status: 'RUNNING_LATE',
    color: 'amber',
    activeAgendaId: 'agenda_c1',
  },
];

export const MOCK_EVENTS = [
  {
    id: 'evt_001',
    title: 'Global AI Summit 2026',
    subtitle: 'The Next Frontier in Autonomous Systems',
    status: 'LIVE',
    location: 'Tech Center Complex',
    date: '2026-09-19',
    startTime: '09:00 AM',
    endTime: '05:00 PM',
    activeSpeakerId: 'spk_1',
    activeAgendaId: 'agenda_02',
    totalAttendees: 1420,
    timeDriftMinutes: 10,
    tracks: MOCK_TRACKS,
  },
  {
    id: 'evt_002',
    title: 'DevCon Keynote Showcase',
    subtitle: 'Building Intelligent Realtime Applications',
    status: 'UPCOMING',
    location: 'Hall B',
    date: '2026-09-20',
    startTime: '10:00 AM',
    endTime: '04:30 PM',
    activeSpeakerId: null,
    activeAgendaId: null,
    totalAttendees: 850,
    timeDriftMinutes: 0,
    tracks: MOCK_TRACKS,
  },
];

export const MOCK_AGENDA = [
  // ================= TRACK A =================
  {
    id: 'agenda_01',
    eventId: 'evt_001',
    trackId: 'track_a',
    trackName: 'TRACK A — MAIN STAGE',
    title: 'Welcome Address & Keynote Intro',
    description: 'Setting the stage for Global AI Summit 2026 with opening remarks and sponsor acknowledgments.',
    speakerId: 'spk_3',
    speakerName: 'Dr. Aris Thorne',
    startTime: '09:00 AM',
    endTime: '09:15 AM',
    allocatedMinutes: 15,
    actualMinutes: 14,
    status: 'COMPLETED',
    order: 1,
    teleprompterScript: 'Welcome everyone to the Global AI Summit 2026! Today we bring together 1,400 visionaries, engineers, and researchers...',
  },
  {
    id: 'agenda_02',
    eventId: 'evt_001',
    trackId: 'track_a',
    trackName: 'TRACK A — MAIN STAGE',
    title: 'Generative AI at Scale: Infrastructure & Models',
    description: 'Deep dive into training multi-trillion parameter neural networks across distributed GPU clusters.',
    speakerId: 'spk_1',
    speakerName: 'Dr. Sophia Chen',
    startTime: '09:15 AM',
    endTime: '09:50 AM',
    allocatedMinutes: 35,
    remainingSeconds: 840,
    status: 'LIVE',
    order: 2,
    teleprompterScript: 'Ladies and gentlemen, please welcome Dr. Sophia Chen, Chief AI Scientist at NeuralScale. Sophia will be uncovering how next-gen LLM training paradigms solve latency bottlenecks in live production environments.',
  },
  {
    id: 'agenda_03',
    eventId: 'evt_001',
    trackId: 'track_a',
    trackName: 'TRACK A — MAIN STAGE',
    title: 'Panel: Ethics, Regulation & Safety in Autonomous AI',
    description: 'Interactive panel featuring policy leaders, ethicists, and tech executives.',
    speakerId: 'spk_2',
    speakerName: 'Marcus Vance & Panelists',
    startTime: '09:50 AM',
    endTime: '10:35 AM',
    allocatedMinutes: 45,
    status: 'UPCOMING',
    order: 3,
    teleprompterScript: 'Up next, we dive into one of the most critical discussions of the decade: Ethics and Regulatory Frameworks in AI. Please give a warm welcome to our moderator Marcus Vance and our esteemed panel.',
  },
  {
    id: 'agenda_04',
    eventId: 'evt_001',
    trackId: 'track_a',
    trackName: 'TRACK A — MAIN STAGE',
    title: 'Coffee & Keynote Break',
    description: 'Main foyer exhibit hall showcase and sponsor lounge networking.',
    speakerId: null,
    speakerName: 'None',
    startTime: '10:35 AM',
    endTime: '11:00 AM',
    allocatedMinutes: 25,
    status: 'UPCOMING',
    order: 4,
    teleprompterScript: 'We are now taking a short 25-minute networking break. Grab a coffee at the foyer exhibit hall and connect with our sponsors!',
  },

  // ================= TRACK B =================
  {
    id: 'agenda_b1',
    eventId: 'evt_001',
    trackId: 'track_b',
    trackName: 'TRACK B — WORKSHOP HALL',
    title: 'Hands-On LLM Fine-Tuning & Quantization Lab',
    description: 'Practical tutorial on QLoRA, vLLM acceleration, and 4-bit model deployment.',
    speakerId: 'spk_b1',
    speakerName: 'Sarah Jenkins',
    startTime: '09:30 AM',
    endTime: '10:30 AM',
    allocatedMinutes: 60,
    status: 'COMPLETED',
    order: 1,
    teleprompterScript: 'Welcome to Workshop Hall B! Today Sarah Jenkins will guide us step-by-step through parameter-efficient fine-tuning techniques for open weights models.',
  },
  {
    id: 'agenda_b2',
    eventId: 'evt_001',
    trackId: 'track_b',
    trackName: 'TRACK B — WORKSHOP HALL',
    title: 'Real-Time RAG Architectures & Vector DBs',
    description: 'Building ultra-low-latency semantic search pipelines for enterprise knowledge bases.',
    speakerId: 'spk_b2',
    speakerName: 'David Kumar',
    startTime: '10:30 AM',
    endTime: '11:30 AM',
    allocatedMinutes: 60,
    remainingSeconds: 1200,
    status: 'LIVE',
    order: 2,
    teleprompterScript: 'Welcome David Kumar to Workshop Track B. David will demonstrate sub-10ms retrieval augmented generation using vector indexing.',
  },
  {
    id: 'agenda_b3',
    eventId: 'evt_001',
    trackId: 'track_b',
    trackName: 'TRACK B — WORKSHOP HALL',
    title: 'Edge AI & Embedded Micro-Models',
    description: 'Deploying neural networks to microcontrollers, robotics, and mobile devices.',
    speakerId: 'spk_b3',
    speakerName: 'Elena Vance',
    startTime: '11:30 AM',
    endTime: '12:30 PM',
    allocatedMinutes: 60,
    status: 'UPCOMING',
    order: 3,
    teleprompterScript: 'Next in Workshop Hall B, Elena Vance presents Edge AI for robotics and offline mobile intelligent assistants.',
  },

  // ================= TRACK C =================
  {
    id: 'agenda_c1',
    eventId: 'evt_001',
    trackId: 'track_c',
    trackName: 'TRACK C — NETWORKING LOUNGE',
    title: 'AI Founders & VCs Speed Networking',
    description: 'Structured pitch lounge connecting early-stage AI startups with tier-1 investors.',
    speakerId: 'spk_c1',
    speakerName: 'Alex Morgan',
    startTime: '10:00 AM',
    endTime: '11:00 AM',
    allocatedMinutes: 60,
    remainingSeconds: 900,
    status: 'LIVE',
    order: 1,
    teleprompterScript: 'Welcome to Track C Pitch Lounge! Alex Morgan is moderating speed networking between 20 AI founders and leading venture capitalists.',
  },
  {
    id: 'agenda_c2',
    eventId: 'evt_001',
    trackId: 'track_c',
    trackName: 'TRACK C — NETWORKING LOUNGE',
    title: 'Fireside Chat: The Future of Autonomous Agents',
    description: 'Intimate conversation on multi-agent collaboration, tool execution, and artificial general intelligence.',
    speakerId: 'spk_c2',
    speakerName: 'Samantha Reed & Guests',
    startTime: '11:00 AM',
    endTime: '12:00 PM',
    allocatedMinutes: 60,
    status: 'UPCOMING',
    order: 2,
    teleprompterScript: 'Join us at Foyer Stage C for an intimate fireside chat with Samantha Reed exploring autonomous agent swarm architectures.',
  },
];

export const MOCK_SPEAKERS = [
  {
    id: 'spk_1',
    name: 'Dr. Sophia Chen',
    role: 'Chief AI Scientist',
    company: 'NeuralScale',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    status: 'ON STAGE',
    trackId: 'track_a',
    topic: 'Generative AI at Scale',
    slidesReady: true,
    micAssigned: 'Wireless Mic 1',
    keyPoints: [
      'Scaling laws in 2026 models',
      'Distributed training efficiency',
      'Real-time inference optimization',
    ],
    bio: 'Pioneer in distributed deep learning with over 15 patents. Former principal researcher at AI Research Labs.',
  },
  {
    id: 'spk_2',
    name: 'Marcus Vance',
    role: 'Lead Live Event Anchor',
    company: 'StagePilot Studios',
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80',
    status: 'READY',
    trackId: 'track_a',
    topic: 'Ethics & Safety Panel Moderator',
    slidesReady: true,
    micAssigned: 'Podium Mic 2',
    keyPoints: [
      'Introduce policy directives',
      'Guide Q&A queue from crowd',
      'Keep session strictly under 45 mins',
    ],
    bio: 'Veteran keynote moderator with over 100 live broadcast events managed worldwide.',
  },
  {
    id: 'spk_3',
    name: 'Dr. Aris Thorne',
    role: 'VP of Product',
    company: 'Autonomous Systems Inc.',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    status: 'COMPLETED',
    trackId: 'track_a',
    topic: 'Welcome Address',
    slidesReady: true,
    micAssigned: 'Headset Mic A',
    keyPoints: [
      'Summit theme announcement',
      'Sponsor appreciation',
    ],
    bio: 'Product strategist leading next-generation enterprise AI software suites.',
  },
  {
    id: 'spk_b2',
    name: 'David Kumar',
    role: 'Principal Engineer',
    company: 'VectorData',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
    status: 'ON STAGE',
    trackId: 'track_b',
    topic: 'Real-Time RAG Architectures',
    slidesReady: true,
    micAssigned: 'Workshop Lapel 1',
    keyPoints: ['Vector indexing algorithms', 'HNSW latency benchmarks', 'Hybrid keyword-semantic search'],
    bio: 'Database architect behind high-throughput vector search engines.',
  },
  {
    id: 'spk_c1',
    name: 'Alex Morgan',
    role: 'Managing Director',
    company: 'Visionary Capital',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
    status: 'ON STAGE',
    trackId: 'track_c',
    topic: 'AI Founders & VCs Pitch Lounge',
    slidesReady: true,
    micAssigned: 'Lounge Handheld',
    keyPoints: ['Seed to Series A trends', 'Evaluating moat in wrapper vs core AI', 'Matchmaking queue'],
    bio: 'Venture capitalist focusing on seed-stage AI startups.',
  },
];

export const MOCK_AI_SUGGESTIONS = [
  {
    id: 'sug_1',
    trackId: 'track_a',
    type: 'TIMING_ALERT',
    level: 'warning',
    timestamp: '09:28 AM',
    title: 'Track A is 10 mins behind pace',
    content: 'Dr. Sophia Chen is extending GPU benchmarks slide. Recommend adjusting Q&A duration to preserve panel start time.',
    actionText: 'Push Q&A Prompt to Teleprompter',
  },
  {
    id: 'sug_2',
    trackId: 'track_b',
    type: 'CUE_CARD',
    level: 'info',
    timestamp: '10:32 AM',
    title: 'Track B On Schedule',
    content: 'David Kumar is ready in Workshop Hall B with slides uploaded and mic live.',
    actionText: 'Send Alert to Anchor',
  },
  {
    id: 'sug_3',
    trackId: 'track_a',
    type: 'SENTIMENT',
    level: 'success',
    timestamp: '09:31 AM',
    title: 'High Audience Engagement (88%)',
    content: 'Live audience feedback indicates high interest in GPU latency benchmark comparisons.',
    actionText: 'Highlight Topic',
  },
];
