export const MOCK_USER_ORGANIZER = {
  id: 'usr_org_101',
  name: 'Elena Rostova',
  email: 'elena@stagepilot.io',
  role: 'organizer',
  avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  eventAccess: ['evt_001', 'evt_002'],
};

export const MOCK_USER_ANCHOR = {
  id: 'usr_anc_202',
  name: 'Marcus Vance',
  email: 'marcus@stagepilot.io',
  role: 'anchor',
  avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80',
  assignedStage: 'Main Stage',
};

export const MOCK_EVENTS = [
  {
    id: 'evt_001',
    title: 'Global AI Summit 2026',
    subtitle: 'The Next Frontier in Autonomous Systems',
    status: 'LIVE',
    location: 'Main Auditorium, Tech Center',
    date: '2026-09-19',
    startTime: '09:00 AM',
    endTime: '05:00 PM',
    activeSpeakerId: 'spk_1',
    activeAgendaId: 'agenda_02',
    totalAttendees: 1420,
    timeDriftMinutes: 2, // +2 mins behind schedule
  },
  {
    id: 'evt_002',
    title: 'DevCon Keynote Showcase',
    subtitle: 'Building Intelligent Realtime Applications',
    status: 'UPCOMING',
    location: 'Hall B',
    date: '2026-09-20',
    startTime: '10:00 AM',
    endTime: '04:30 PM',
    activeSpeakerId: null,
    activeAgendaId: null,
    totalAttendees: 850,
    timeDriftMinutes: 0,
  },
];

export const MOCK_AGENDA = [
  {
    id: 'agenda_01',
    eventId: 'evt_001',
    title: 'Welcome Address & Keynote Intro',
    description: 'Setting the stage for Global AI Summit 2026 with opening remarks and sponsor acknowledgments.',
    speakerId: 'spk_3',
    speakerName: 'Dr. Aris Thorne',
    startTime: '09:00 AM',
    allocatedMinutes: 15,
    actualMinutes: 14,
    status: 'COMPLETED',
    order: 1,
    teleprompterScript: 'Welcome everyone to the Global AI Summit 2026! Today we bring together 1,400 visionaries, engineers, and researchers...',
  },
  {
    id: 'agenda_02',
    eventId: 'evt_001',
    title: 'Generative AI at Scale: Infrastructure & Models',
    description: 'Deep dive into training multi-trillion parameter neural networks across distributed GPU clusters.',
    speakerId: 'spk_1',
    speakerName: 'Dr. Sophia Chen',
    startTime: '09:15 AM',
    allocatedMinutes: 35,
    remainingSeconds: 840, // 14 mins remaining
    status: 'LIVE',
    order: 2,
    teleprompterScript: 'Ladies and gentlemen, please welcome Dr. Sophia Chen, Chief AI Scientist at NeuralScale. Sophia will be uncovering how next-gen LLM training paradigms solve latency bottlenecks in live production environments.',
  },
  {
    id: 'agenda_03',
    eventId: 'evt_001',
    title: 'Panel: Ethics, Regulation & Safety in Autonomous AI',
    description: 'Interactive panel featuring policy leaders, ethicists, and tech executives.',
    speakerId: 'spk_2',
    speakerName: 'Marcus Vance & Panelists',
    startTime: '09:50 AM',
    allocatedMinutes: 45,
    status: 'UPCOMING',
    order: 3,
    teleprompterScript: 'Up next, we dive into one of the most critical discussions of the decade: Ethics and Regulatory Frameworks in AI. Please give a warm welcome to our moderator Marcus Vance and our esteemed panel.',
  },
  {
    id: 'agenda_04',
    eventId: 'evt_001',
    title: 'Coffee & Networking Break',
    description: 'Foyer exhibit hall showcase and sponsor lounge networking.',
    speakerId: null,
    speakerName: 'None',
    startTime: '10:35 AM',
    allocatedMinutes: 25,
    status: 'UPCOMING',
    order: 4,
    teleprompterScript: 'We are now taking a short 25-minute networking break. Grab a coffee at the foyer exhibit hall and connect with our sponsors!',
  },
];

export const MOCK_SPEAKERS = [
  {
    id: 'spk_1',
    name: 'Dr. Sophia Chen',
    role: 'Chief AI Scientist',
    company: 'NeuralScale',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
    status: 'ON STAGE',
    topic: 'Generative AI at Scale',
    slidesReady: true,
    micAssigned: 'Wireless Mic 1',
    keyPoints: [
      'Scaling laws in 2026 models',
      'Distributed training efficiency',
      'Real-time inference optimization',
    ],
    bio: 'Pioneer in distributed deep learning with over 15 patents. Former principal researcher at AI Research Labs.',
  },
  {
    id: 'spk_2',
    name: 'Marcus Vance',
    role: 'Lead Live Event Anchor',
    company: 'StagePilot Studios',
    avatar: 'https://images.unsplash.com/photo-1560250097-0b93528c311a?w=150&auto=format&fit=crop&q=80',
    status: 'READY',
    topic: 'Ethics & Safety Panel Moderator',
    slidesReady: true,
    micAssigned: 'Podium Mic 2',
    keyPoints: [
      'Introduce policy directives',
      'Guide Q&A queue from crowd',
      'Keep session strictly under 45 mins',
    ],
    bio: 'Veteran keynote moderator with over 100 live broadcast events managed worldwide.',
  },
  {
    id: 'spk_3',
    name: 'Dr. Aris Thorne',
    role: 'VP of Product',
    company: 'Autonomous Systems Inc.',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
    status: 'COMPLETED',
    topic: 'Welcome Address',
    slidesReady: true,
    micAssigned: 'Headset Mic A',
    keyPoints: [
      'Summit theme announcement',
      'Sponsor appreciation',
    ],
    bio: 'Product strategist leading next-generation enterprise AI software suites.',
  },
];

export const MOCK_AI_SUGGESTIONS = [
  {
    id: 'sug_1',
    type: 'TIMING_ALERT',
    level: 'warning',
    timestamp: '09:28 AM',
    title: 'Speaker is 3 mins ahead of pace',
    content: 'Dr. Sophia Chen is reaching final slides early. Suggest introducing a 2-minute audience Q&A before transitioning to the panel.',
    actionText: 'Push Q&A Prompt to Teleprompter',
  },
  {
    id: 'sug_2',
    type: 'CUE_CARD',
    level: 'info',
    timestamp: '09:30 AM',
    title: 'Stage Transition Note',
    content: 'Ensure Marcus Vance is on stage position B before slide 24 ends.',
    actionText: 'Send Alert to Anchor',
  },
  {
    id: 'sug_3',
    type: 'SENTIMENT',
    level: 'success',
    timestamp: '09:31 AM',
    title: 'High Audience Engagement (88%)',
    content: 'Live audience feedback indicates high interest in GPU latency benchmark comparisons.',
    actionText: 'Highlight Topic',
  },
];
